server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testing_order_relatedTables                 # kid_toys
    username: root
    password: 12345
  #      //CHANGE -this to frank sir---->url

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


####################################################################################################
#  spring.jpa.hibernate.ddl-auto=create  --- Creates tables every time (recreates schema)
#  spring.jpa.hibernate.ddl-auto=update  --- Updates existing schema without losing data
#  spring.jpa.hibernate.ddl-auto=validate -- Validates schema without creating/updating tables
#  spring.jpa.hibernate.ddl-auto=none  ----- No schema creation or validation

#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
                                        # NET-CHECK WHAT IS MEANT BY THIS ?

#  Debug Bean Creation :
#     Enable debug logs for Spring to inspect bean creation and context initialization issues.
#     Add the following to your application.properties:
#             logging.level.org.springframework=DEBUG
#     Look for logs that mention the ModelMapper bean during startup to understand why it isn't
#     being registered.